### ISSUE TITLE
Suggested order change in material

### ISSUE THREAD

**Issue by SamirEvan** [learn-co-curriculum/dsc-1-07-07-object-oriented-shopping-cart-lab#2]
For students who are relatively new to Python and to coding, the solution to this lab is unintelligible. However, the bulk of the confusion could be solved by placing the Class Variables and Instance Methods Readme before the Shopping Cart Lab. At a minimum, it would be helpful to mention decorators in the lab so students know what to research (simply searching "what does @ mean in python" sent me on a wild goose chase).

**Comment by mathymitchell** [comment]
Accurate assessment. This lab was originally at a later date and made reference to decorators in the solution which students had not been exposed to. Lab has been updated to simplify this, removing all references to decorators and simplifying the solution.
